"""
Модуль экспорта действий в различные форматы
"""

import re
from datetime import datetime
from typing import Optional

from backend.core import TaskBoard, TaskRow, Action, ActionType, Coordinates


class ActionExporter:
    """Экспорт действий в различные форматы"""
    
    # Шаблоны для AHK v2
    AHK_TEMPLATES = {
        ActionType.MOUSE_CLICK: "Click, {button}, {x}, {y}",
        ActionType.MOUSE_MOVE: "MouseMove, {x}, {y}",
        ActionType.KEY_PRESS: "Send, {{{key}}}",
        ActionType.WAIT_TIME: "Sleep, {ms}",
        ActionType.LOOP: "Loop, {count}\n{{\n    ; действия цикла\n}}",
        ActionType.LOG: "OutputDebug, {message}",
        ActionType.SCREENSHOT: "SaveScreenshot, {path}",
    }
    
    # Шаблоны для Python-скрипта
    PYTHON_TEMPLATES = {
        ActionType.MOUSE_CLICK: "backend.mouse.move_to({x}, {y})\nbackend.mouse.click('{button}')",
        ActionType.MOUSE_MOVE: "backend.mouse.move_to(x={x}, y={y})",
        ActionType.KEY_PRESS: "backend.keyboard.press('{key}')",
        ActionType.WAIT_TIME: "await asyncio.sleep({ms} / 1000)",
        ActionType.LOOP: "for i in range({count}):\n    # действия цикла",
        ActionType.LOG: "print('[LOG] {message}')",
        ActionType.SCREENSHOT: "backend.screen.take_screenshot(region={region})",
    }
    
    def __init__(self):
        self.config = {
            "ahk_version": "2.0",
            "default_delay_ms": 1000,
        }
    
    def export_to_ahk(self, board: TaskBoard, include_comments: bool = True) -> str:
        """
        Экспорт доски в AHK скрипт
        
        Args:
            board: Доска для экспорта
            include_comments: Включать комментарии
        
        Returns:
            AHK скрипт в виде строки
        """
        script = self._generate_header(board, include_comments)
        
        for row in board.rows:
            if not row.enabled:
                continue
            
            if include_comments:
                script += f"; {'='*50}\n"
                script += f"; Row: {row.name}\n"
                script += f"; {'='*50}\n"
            
            for action in row.actions:
                if not action.enabled:
                    continue
                
                ahk_line = self._action_to_ahk(action)
                if ahk_line:
                    script += ahk_line + "\n"
            
            script += "\n"

        if include_comments:
            script += "}\n"
        
        return script
    
    def _generate_header(self, board: TaskBoard, include_comments: bool) -> str:
        """Сгенерировать заголовок скрипта"""
        header = "; AHK Script generated by AHK Manipulator\n"
        header += f"; Board: {board.name}\n"
        header += f"; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        header += f"; Version: {self.config['ahk_version']}\n"
        header += "\n"
        header += "#Requires AutoHotkey v2.0\n"
        header += "#SingleInstance Force\n"
        header += "\n"
        
        if include_comments:
            header += "; ===== Hotkeys =====\n"
            header += "F1:: ; Запуск скрипта\n"
            header += "    RunScript()\n"
            header += "    return\n"
            header += "\n"
            header += "F2:: ; Остановка\n"
            header += "    ExitApp\n"
            header += "    return\n"
            header += "\n"
            header += "; ===== Main Script =====\n"
            header += "RunScript() {\n"
        
        return header
    
    def _action_to_ahk(self, action: Action) -> Optional[str]:
        """Конвертировать действие в AHK команду"""
        template = self.AHK_TEMPLATES.get(action.action_type)
        
        if not template:
            return f"; Action '{action.name}' not implemented"
        
        try:
            # Подстановка параметров
            params = self._extract_action_params(action)
            line = template.format(**params)
            
            # Добавить задержки если есть
            if action.delay_before_ms > 0:
                line = f"Sleep, {action.delay_before_ms}\n" + line
            
            if action.delay_after_ms > 0:
                line = line + f"\nSleep, {action.delay_after_ms}"
            
            # Добавить повторения
            if action.repeat_count > 1:
                line = f"Loop, {action.repeat_count}\n{{\n    {line}\n}}"
            
            return line
            
        except KeyError as e:
            return f"; Error: Missing parameter {e} for action {action.name}"
    
    def _extract_action_params(self, action: Action) -> dict:
        """Извлечь параметры из действия"""
        params = {
            "id": action.id,
            "name": action.name,
            "button": action.mouse_button,
            "key": action.key or "",
            "x": action.coordinates.x if action.coordinates else 0,
            "y": action.coordinates.y if action.coordinates else 0,
            "ms": action.delay_before_ms or self.config["default_delay_ms"],
            "count": action.metadata.get("iterations", 1),
            "message": action.metadata.get("message", action.name),
            "path": action.metadata.get("save_path", "screenshot.png"),
            "region": action.metadata.get("region", "(0, 0, 0, 0)"),
        }
        return params
    
    def export_to_python(self, board: TaskBoard, include_imports: bool = True) -> str:
        """
        Экспорт доски в Python-скрипт
        
        Args:
            board: Доска для экспорта
            include_imports: Включать импорты
        
        Returns:
            Python скрипт в виде строки
        """
        script = ""
        
        if include_imports:
            script += "# Python Script generated by AHK Manipulator\n"
            script += f"# Board: {board.name}\n"
            script += f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            script += "\n"
            script += "import asyncio\n"
            script += "from backend import BackendApplication, MouseService, KeyboardService, ScreenService\n"
            script += "\n"
            script += "async def run_board():\n"
            script += "    backend = BackendApplication(\n"
            script += "        mouse=MouseService(),\n"
            script += "        keyboard=KeyboardService(),\n"
            script += "        screen=ScreenService()\n"
            script += "    )\n"
            script += "    \n"
        
        for row in board.rows:
            if not row.enabled:
                continue
            
            if include_imports:
                script += f"    # Row: {row.name}\n"
            
            for action in row.actions:
                if not action.enabled:
                    continue
                
                py_line = self._action_to_python(action, indent=4 if include_imports else 0)
                if py_line:
                    script += py_line + "\n"
            
            script += "\n"
        
        if include_imports:
            script += "\nif __name__ == '__main__':\n"
            script += "    asyncio.run(run_board())\n"
        
        return script
    
    def _action_to_python(self, action: Action, indent: int = 4) -> Optional[str]:
        """Конвертировать действие в Python код"""
        template = self.PYTHON_TEMPLATES.get(action.action_type)
        
        if not template:
            return " " * indent + f"# Action '{action.name}' not implemented"
        
        try:
            params = self._extract_action_params(action)
            line = template.format(**params)
            if "\n" in line:
                return "\n".join((" " * indent + part) for part in line.splitlines())
            return " " * indent + line
            
        except KeyError as e:
            return " " * indent + f"# Error: Missing parameter {e}"
    
    def export_to_json(self, board: TaskBoard) -> dict:
        """Экспорт доски в JSON (для сохранения)"""
        return board.to_dict()
